<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class Siades_idm extends Seeder
{
    public function run()
    {
        $data = [
            [
                "idm" => " Skor Akses Sarkes ",
                "skor" => " 5 ",
                "keterangan" => " Waktu tempuh dari ≤ 30 Menit ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " Dinkes, PU ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Dokter ",
                "skor" => " 0 ",
                "keterangan" => " Jumlah Dokter Tidak ada ",
                "kegiatan" =>  " Pengadaan Min 1 org Dokter ",
                "nilai" =>  " 0.00952381 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DINKES ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Bidan ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah bidan ≥ 1 orang ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DINKES ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Nakes Lain ",
                "skor" => " 2 ",
                "keterangan" => " Jumlah tenaga kesehatan lainnya 1 orang ",
                "kegiatan" =>  " Penambahan Nakes Min 4 Org ",
                "nilai" =>  " 0.00571429 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DINKES ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Tingkat Kepesertaan BPJS ",
                "skor" => " 2 ",
                "keterangan" => " Jumlah peserta BPJS/jumlah penduduk antara 0,1 s.d 0,25 ",
                "kegiatan" =>  " Fasilitasi kepesertaan BPJS warga Desa hingga &gt; 75% ",
                "nilai" =>  " 0.00571429 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DINKES ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  " BPJS ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses Poskesdes ",
                "skor" => " 5 ",
                "keterangan" => " Jarak tempuh menuju Poskesdes = 500 Meter ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DINKES ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Aktivitas Posyandu ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Posyandu aktif 1 bulan sekali/ Jumlah Posyandu &gt; 0,75 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => " DPMD ",
                "kab" => " DPMD, DINKES ",
                "des" => " DD ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses SD/MI ",
                "skor" => " 5 ",
                "keterangan" => " Jarak tempuh menuju SD atau MI = 3000 Meter ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISDIK, PU ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses SMP/MTS ",
                "skor" => " 5 ",
                "keterangan" => " Jarak tempuh menuju SMP atau MTs ≤ 6000 Meter ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISDIK, PU ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses SMA/SMK ",
                "skor" => " 5 ",
                "keterangan" => " Jarak tempuh menuju SMU atau SMK ≤ 6000 Meter ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => " DISDIK ",
                "kab" => " PU ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Ketersediaan PAUD ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah PAUD ≥ 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => " DISDIK ",
                "kab" => " DISDIK ",
                "des" => " DD ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Ketersediaan PKBM/ Paket ABC ",
                "skor" => " 1 ",
                "keterangan" => " Jumlah PKBM atau Paket ABC Tidak ada ",
                "kegiatan" =>  " Pelaksanaan Kegiatan PKBM/Kejar Paket A B C ",
                "nilai" =>  " 0.00761905 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISDIK ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Ketersediaan Kursus ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Pusat Keterampilan atau Kursus ≥ 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => "-",
                "csr" => " CSR ",
                "lainnya" =>  " Swasta, Perorangan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Ketersediaan Taman Baca/ Perpus Desa ",
                "skor" => " 1 ",
                "keterangan" => " Taman Bacaan Masyarakat atau perpustakaan Desa tidak tersedia ",
                "kegiatan" =>  " Pembangunan PerpusDes/Taman Bacaan Mayarakat ",
                "nilai" =>  " 0.00761905 ",
                "pusat" => " Kemenperpus Arsip ",
                "prov" => " Dinas Perpus ",
                "kab" => " Dinas Perpus ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Kebiasaan Goryong ",
                "skor" => " 5 ",
                "keterangan" => " Terdapat Kebiasaan Gotong Royong ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Frekuensi Goryong ",
                "skor" => " 5 ",
                "keterangan" => " Frekuensi Gotong Royong &gt; 2 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Ketersediaan Ruang Publik ",
                "skor" => " 5 ",
                "keterangan" => " Ruang Publik terdapat didesa ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " PU ",
                "des" => " DD ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Kelompok OR ",
                "skor" => " 3 ",
                "keterangan" => " Jumlah kelompok kegiatan olahraga antara 4 s.d 5 ",
                "kegiatan" =>  " Penambahan Min 4 Kelp Olahraga ",
                "nilai" =>  " 0.00380952 ",
                "pusat" => "-",
                "prov" => " DISPORA ",
                "kab" => " DISPORA ",
                "des" => " Karang Taruna ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Kegiatan OR ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah kegiatan olahraga &gt; 7 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => " Kemepora/ Kemendes ",
                "prov" => " DISPORA ",
                "kab" => " DISPORA ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  " Perorangan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Keragaman Agama ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Jenis Agama di Desa &gt; 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Keragaman Bahasa ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Bahasa yang digunakan sehari-hari &gt; 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Keragaman Komunikasi ",
                "skor" => " 5 ",
                "keterangan" => " Warga Desa terdiri dari Suku &gt; 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Poskamling ",
                "skor" => " 5 ",
                "keterangan" => " Terdapat Pos Keamanan di Desa ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " DD ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Siskamling ",
                "skor" => " 5 ",
                "keterangan" => " Terdapat Sistem Keamanan Lingkungan warga di Desa ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Konflik ",
                "skor" => " 1 ",
                "keterangan" => " Terdapat atau ada Konflik di Desa ",
                "kegiatan" =>  " Identifikasi dan Penanganan Konflik ",
                "nilai" =>  " 0.00761905 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " Kesbangpol ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor PMKS ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah PMKS tidak ada atau 0 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " Dinsos ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor SLB ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Skor SLB = 0 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => " DIKNAS ",
                "kab" => "-",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses Listrik ",
                "skor" => " 5 ",
                "keterangan" => " (Jumlah Keluarga Memakai listrik + non Listrik/Jumlah keluarga memakai listrik) ≥ 0,9 ) ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => " ESDM ",
                "prov" => " ESDM ",
                "kab" => "-",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  " Perorangan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Sinyal Tlp ",
                "skor" => " 5 ",
                "keterangan" => " Sinyal telepon seluler di Desa Kuat ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => " Kominfo ",
                "prov" => " Diskominfo ",
                "kab" => " Diskominfo ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  " Operator Selular ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Internet Kantor Desa ",
                "skor" => " 5 ",
                "keterangan" => " Terdapat fasilitas internet di kantor Desa ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => " Kominfo/ Kemendes ",
                "prov" => "-",
                "kab" => "-",
                "des" => " Desa ",
                "csr" => " CSR ",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses Internet Warga ",
                "skor" => " 5 ",
                "keterangan" => " Terdapat Akses internet warga di Desa ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => " Kominfo ",
                "prov" => " Diskominfo ",
                "kab" => " Diskominfo ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  " Operator Selular ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Akses Jamban ",
                "skor" => " 5 ",
                "keterangan" => " Warga Desa BAB di Jamban Sendiri ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DINSOS,DINKES ",
                "des" => "-",
                "csr" => " CSR ",
                "lainnya" =>  " Perorangan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Sampah ",
                "skor" => " 5 ",
                "keterangan" => " Warga desa membuang sampah di Tempat Sampah kemudian diangkut ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => " DLH ",
                "kab" => " DLH, DKPP ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Air Minum ",
                "skor" => " 5 ",
                "keterangan" => " Sumber air minum berasal dari PAM, Air Ledeng tanpa Meteran ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => " PAMSIMAS, PU ",
                "prov" => "-",
                "kab" => " PU ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  " PDAM ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Air Mandi &amp; Cuci ",
                "skor" => " 4 ",
                "keterangan" => " Sumber air mandi dan cuci berasal dari Sumur Bor/pompa, Sumur ",
                "kegiatan" =>  " Pemasangan PDAM/Air Ledeng Tanpa Meteran ",
                "nilai" =>  " 0.00190476 ",
                "pusat" => " PAMSIMAS, PU ",
                "prov" => "-",
                "kab" => " PU ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  " PDAM ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " IKS 2022 ",
                "skor" => " 0.85142857142857 ",
                "keterangan" => "-",
                "kegiatan" =>  "-",
                "nilai" =>  "-",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Keragaman Produksi ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Industri Mikro/ Jumlah KK ≥ 0,004 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => " DISPERINDAKOP UKM ",
                "kab" => " DISPERINDAKOP UKM ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  " Perorangan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Pertokoan ",
                "skor" => " 5 ",
                "keterangan" => " Jarak ke kelompok pertokoan terdekat ≤ 7 KM ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISPERINDAKOP UKM ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  " Perorangan, Swasta ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Pasar ",
                "skor" => " 3 ",
                "keterangan" => " (Total KK/jumlah pasar(permanen)) antara 0,001 s.d 250 ",
                "kegiatan" =>  " Optimalisasi Pasar ",
                "nilai" =>  " 0.01111111 ",
                "pusat" => " Kemenperind, Kemendes ",
                "prov" => " DISPERINDAKOP UKM ",
                "kab" => " DISPERINDAKOP UKM ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Toko/ Warung Kelontong ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah Toko dan warung kelontong &gt; 3 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " DD ",
                "csr" => "-",
                "lainnya" =>  " Perorangan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Kedai &amp; Penginapan ",
                "skor" => " 3 ",
                "keterangan" => " Jumlah Kedai dan Penginapan = 1 ",
                "kegiatan" =>  " Pembangunan 1 Unit Penginapan ",
                "nilai" =>  " 0.01111111 ",
                "pusat" => "-",
                "prov" => " Dinas Pariwisata ",
                "kab" => " Dinas Pariwisata ",
                "des" => " DD ",
                "csr" => "-",
                "lainnya" =>  " Perorangan, Swasta ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor POS &amp; Logistik ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah pos dan jasa logistik &gt; 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => " BUMDES ",
                "csr" => "-",
                "lainnya" =>  " Kantor Pos, Swasta ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Bank &amp; BPR ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah bank dan BPR &gt; 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => "-",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  " Perbankan ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Kredit ",
                "skor" => " 2 ",
                "keterangan" => " Jumlah fasilitas kredit = 1 ",
                "kegiatan" =>  " Penambahan 3 jenis Fasilitas Kredit (KUR/KKPE/KUK/Kredit lainnya)(Identifikasi kekurangan akses kredit) ",
                "nilai" =>  " 0.01666667 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISPERINDAKOP UKM ",
                "des" => " BUMDES/ Koperasi ",
                "csr" => "-",
                "lainnya" =>  " Bank, Swasta ",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Lembaga Ekonomi ",
                "skor" => " 5 ",
                "keterangan" => " Jumlah koperasi aktif dan BUMDESA &gt; 1 ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISPERINDAKOP UKM ",
                "des" => " Desa ",
                "csr" => " CSR ",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Moda Transportasi Umum ",
                "skor" => " 5 ",
                "keterangan" => " Transportasi Umum ada dengan trayek tetap ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " DISHUB ",
                "des" => "-",
                "csr" => "-",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Keterbukaan Wilayah ",
                "skor" => " 5 ",
                "keterangan" => " Jalan di Desa dilalui oleh kendaraan bermotor roda empat atau lebih Sepanjang Tahun ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " PU ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
            [
                "idm" => " Skor Kualitas Jalan ",
                "skor" => " 5 ",
                "keterangan" => " Jenis permukaan jalan desa Aspal atau beton ",
                "kegiatan" =>  " - ",
                "nilai" =>  " 0 ",
                "pusat" => "-",
                "prov" => "-",
                "kab" => " PU ",
                "des" => " DD ",
                "csr" => " CSR ",
                "lainnya" =>  "-",
                'created_at' => Time::now(),
                'update_at' => Time::now(),
            ],
        ];



        // Simple Queries
        // $this->db->query('INSERT INTO siades_idm (name, description) VALUES(:name:, :description:)', $data);

        // Using Query Builder
        // $this->db->table('siades_idm')->insert($data);

        $this->db->table('siades_idm')->insertBatch($data);
        // php spark db:seed Siades_idm
    }
}
